services:
  - type: web
    name: kamtrud-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    autoDeploy: false  # Включи, если используешь GitHub